### ISSUE TITLE
Rebuild packages in copr with fedora-review

### ISSUE THREAD

**Issue by gotmax23** [mikelolasagasti/github-cli#1]
@mikelolasagasti, 

Can you please rebuild the packages in https://copr.fedorainfracloud.org/coprs/mikelo2/github-cli/ with fedora-review. This will make reviewing the packages a lot easier. You can do so by enabling the `Run fedora-review tool for packages in this project` option under `Settings > Project Details > 3. Other options` and then rebuilding the packages

Thanks,
Maxwell

**Comment by mikelolasagasti** [comment]
Thanks for taking time for reviewing this set of packages @gotmax23 

I just built everything with fedora-review enabled: https://copr.fedorainfracloud.org/coprs/mikelo2/github-cli/packages/

I need to go through each of them and check for updates as the repo is 2 months old already. As I wrote on the gojq BZ the new version even removes one dep. I'll need a couple of days to check everything.
